# App information
name: mobileKKM
description: Nieoficjalna aplikacja do obsługi mobilnej wersji KKM na urządzeniach mobilnych.
price: Bezpłatna

# Download buttons
download:
  playstore: https://play.google.com/store/apps/details?id=de.codebucket.mkkm&utm_source=landing-page
  appgallery: https://appgallery.cloud.huawei.com/ag/n/app/C103078099?channelId=landing-page

# Feature list
features:
  - title: GitHub Pages Jekyll Theme
    description: Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name: magic
    
  - title: iPhone Device Preview
    description: Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name: mobile

  - title: Video Support
    description: Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name: play-circle

  - title: Automatic Icon and Metadata
    description: Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name: sync

  - title: Easy to Tweak
    description: Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: adjust

  - title: Feature List
    description: Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: star

  - title: Smart App Banner
    description: Display a smart app banner on iOS devices.
    fontawesome_icon_name: arrow-alt-circle-down

  - title: Social Links
    description: Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: link

  - title: FontAwesome Support
    description: Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name: info-circle

  - title: # New Feature Title
    description: # New Feature Description
    fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.
